<?php
function deleteCookie($cookieName){
    // Deletes and unsets a cookie
    setcookie($cookieName, "", time() - 1, "/");
    unset($_COOKIE[$cookieName]);
}

function filterAlphanumeric($input){
    // Filter that only allows alphanumeric characters
    $filter = '/^[a-zA-Z0-9]+$/';

    // Simple if-else check. Returns "true" if correct, "false" if wrong
    if(preg_match($filter, $input)){
        return true;
    }
    else{
        return false;
    }
}

function filterDate($input){
    // Y-m-d H:i regex filter
    $filter = '/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/';

    // Simple if-else check. Returns "true" if correct, "false" if wrong
    if(preg_match($filter, $input)){
        return true;
    }
    else{
        return false;
    }
}

function filterEmail($input){
    // Email regex filter
    $filter = '/^[a-zA-Z0-9\._-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]{2,6}$/';

    // Simple if-else check. Returns "true" if correct, "false" if wrong
    if(preg_match($filter, $input)){
        return true;
    }
    else{
        return false;
    }
}

function filterID($input){
    // 'KLD-xx-xxxxxx' regex filter, with x being a number
    $filter = '/^KLD-[0-9]{2}-[0-9]{6}$/';

    // Simple if-else check. Returns "true" if correct, "false" if wrong
    if(preg_match($filter, $input)){
        return true;
    }
    else{
        return false;
    }
}

function filterLoop($regex, $array) { // Runs preg_match on every array element
    for($i = 0; $i < count($array); $i++){
        if(!preg_match($regex, $array[$i])){
            return false;
        }
    }
    return true;
}

function filterName($input){
    // Name regex filter
    $filter = '/^[a-zA-Z\s]{0,32}$/';

    // Simple if-else check. Returns "true" if correct, "false" if wrong
    if(preg_match($filter, $input)){
        return true;
    }
    else{
        return false;
    }
}
function filterPassword($input){
    // Filter that only allows alphanumeric characters and some special characters
    $filter = '/^[a-zA-Z0-9\!@$^&-._]{8,32}+$/';

    // Simple if-else check. Returns "true" if correct, "false" if wrong
    if(preg_match($filter, $input)){
        return true;
    }
    else{
        return false;
    }
}

function generateNumber($length){
    // Numbers generated by the function
    $numbers = '0123456789';
    $numbersLength = strlen($numbers);

    $randomString = '';
    // Generate random numbers from the number set
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $numbers[random_int(0, $numbersLength - 1)];
    }

    return $randomString;
}

function lowercaseNumericString($length) {
    // Characters generated by the function
    $characters = 'abcdefghijklmnopqrstuvwxyz0123456789';
    $charactersLength = strlen($characters);

    $randomString = '';
    // Generate random characters from the character set
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[random_int(0, $charactersLength - 1)];
    }

    return $randomString;
}

function sanitizeInput($input){
    $input = htmlspecialchars(stripslashes(trim($input)));

    return $input;
}
?>